---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: sort-simple-yaml
        files: ^vars/(.*).yml$
      - id: check-added-large-files
        args: ['--maxkb=6000']
      - id: no-commit-to-branch
        args: [--branch, main]
