---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: sort-simple-yaml
        files: ^vars/(.*).yml$
      - id: check-added-large-files
        args: [--maxkb=3000]

  - repo: https://github.com/ansible/ansible-lint
    rev: v6.16.2
    hooks:
      - id: ansible-lint
        additional_dependencies:
          - ansible==7.3.0
        exclude: .pre-commit-config.yaml
        args: [--write]

  - repo: local
    hooks:
      - id: pre-commit-check-mode
        name: Check mode
        entry: ansible-playbook --syntax-check --check playbook.yml
        language: system
        files: ^playbook\.yml$
        exclude: .pre-commit-config.yaml

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [--config-file=.yamllint.yml]
        files: \.(yml|yaml)$
        exclude: .pre-commit-config.yaml
