---
- name: Run dotfiles pre-flight checks
  ansible.builtin.include_tasks: preflight.yml
  tags: [always, preflight]
- name: Revert dotfiles
  ansible.builtin.include_tasks: revert.yml
  tags: revert_dotfiles

- name: Handle legacy dotfiles
  ansible.builtin.include_tasks: legacy.yml
  tags: setup

- name: Handle sv dotfiles
  ansible.builtin.include_tasks: sv.yml
  tags: setup

- name: Link dotfiles
  ansible.builtin.include_tasks: link.yml
  tags: setup
