---
- name: Create font directory if it doesn't exist
  ansible.builtin.file:
    path: ~/Library/Fonts/FiraCode
    state: directory
    mode: "0755"
  tags:
    - setup
    - fonts

- name: Download Fira Code font from GitHub
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/FiraCode.zip
    dest: /tmp/Fira_Code_v2.3.3.zip
    mode: "0644"
  tags:
    - setup
    - fonts

- name: Unzip fonts
  ansible.builtin.command:
    cmd: unzip -o -j /tmp/Fira_Code_v2.3.3.zip -d {{ ansible_env.HOME }}/Library/Fonts
    removes: /tmp/Fira_Code_v2.3.3.zip
  tags:
    - setup
    - fonts
    - skip_ansible_lint
