---
- name: Create font directory if it doesn't exist
  ansible.builtin.file:
    path: ~/Library/Fonts/FiraCode
    state: directory
    mode: "0755"
  tags:
    - setup
    - fonts

- name: Find all font files
  ansible.builtin.find:
    paths: "{{ role_path }}/files/FiraCode"
  register: files_to_copy
  tags:
    - setup
    - fonts
    - skip_ansible_lint

- name: Copy each file to the remote destination
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/Library/Fonts/FiraCode/{{ item.path | basename }}"
  loop: "{{ files_to_copy.files }}"
  tags:
    - setup
    - fonts
    - skip_ansible_lint
