---
- name: Remove symlinks for Visual Studio Code configuration files
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    state: absent
  loop:
    - { dest: ~/Library/Application Support/Code - Insiders/User/keybindings.json }
    - { dest: ~/Library/Application Support/Code - Insiders/User/settings.json }
    - { dest: ~/Library/Application Support/Code - Insiders/User/snippets }
  tags:
    - cleanup
    - vscode

- name: Create symlinks for Visual Studio Code configuration files
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - { src: ~/.code/keybindings.json, dest: ~/Library/Application Support/Code - Insiders/User/keybindings.json }
    - { src: ~/.code/settings.json, dest: ~/Library/Application Support/Code - Insiders/User/settings.json }
    - { src: ~/.code/snippets, dest: ~/Library/Application Support/Code - Insiders/User/snippets }
  tags:
    - setup
    - vscode

- name: Install Visual Studio Code extensions
  ansible.builtin.command:
    cmd: code-insiders --install-extension {{ item }}
  loop:
    - redhat.vscode-yaml
    - systemticks.c4-dsl-extension
    - stackbreak.comment-divider
    - EditorConfig.EditorConfig
    - jakebecker.elixir-ls
    - kokakiwi.vscode-just
    - mattn.lisp
    - ms-vsliveshare.vsliveshare
    - yzhang.markdown-all-in-one
    - zhuangtongfa.material-theme
    - ms-python.vscode-pylance
    - ms-python.python
    - rust-lang.rust-analyzer
    - karunamurti.tera
    - tamasfe.even-better-toml
    - github.vscode-pull-request-github
    - github.github-vscode-theme
    - orta.vscode-jest
    - firsttris.vscode-jest-runner
    - andys8.jest-snippets
    - aaron-bond.better-comments
    - mathiasfrohlich.kotlin
    - bierner.markdown-mermaid
    - ahmadalli.vscode-nginx-conf
    - christian-kohler.npm-intellisense
    - 4ops.terraform
    - vscode-icons-team.vscode-icons
    - phoenixframework.phoenix
    - bazelbuild.vscode-bazel
    - oderwat.indent-rainbow
    - bradlc.vscode-tailwindcss
    - samuel-pordeus.elixir-test
    - robbowen.synthwave-vscode
    - vadimcn.vscode-lldb
    - phoenix-liveview-snippets.phoenix-liveview-snippets
    - mechatroner.rainbow-csv
    - dwrolvink.obsidian-dark-theme-rust
    - github.vscode-github-actions
    - takumii.markdowntable
    - heybourn.headwind
    - stivo.tailwind-fold
    - streetsidesoftware.code-spell-checker
    - vscodevim.vim
    - iulian-radu-at.find-unused-exports
    - continue.continue
    - esbenp.prettier-vscode
  tags:
    - setup
    - vscode
    - skip_ansible_lint
