---
- name: Create symlinks for Visual Studio Code configuration files
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - { src: ~/.code/keybindings.json, dest: ~/Library/Application Support/Code/User/keybindings.json }
    - { src: ~/.code/settings.json, dest: ~/Library/Application Support/Code/User/settings.json }
    - { src: ~/.code/snippets, dest: ~/Library/Application Support/Code/User/snippets }
  tags:
    - setup
    - vscode

- name: Install Visual Studio Code extensions
  ansible.builtin.command:
    cmd: code --install-extension {{ item }}
  loop:
    - redhat.vscode-yaml
    - bungcip.better-toml
    - systemticks.c4-dsl-extension
    - stackbreak.comment-divider
    - EditorConfig.EditorConfig
    - jakebecker.elixir-ls
    - github.copilot
    - kokakiwi.vscode-just
    - mattn.lisp
    - ms-vsliveshare.vsliveshare
    - yzhang.markdown-all-in-one
    - zhuangtongfa.material-theme
    - ms-python.vscode-pylance
    - ms-python.python
    - rust-lang.rust-analyzer
    - karunamurti.tera
    - github.copilot-labs
    - tamasfe.even-better-toml
    - github.vscode-pull-request-github
    - github.github-vscode-theme
    - orta.vscode-jest
    - firsttris.vscode-jest-runner
    - andys8.jest-snippets
  tags:
    - setup
    - vscode
